# Default values for iotapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

application:
  name: iot-test
  istioInject: false
  image: ghcr.io/djsasha777/iot/iot/iotbackend:0741895
  svc:
    - name: main
      port: 8088
    - name: monitoring
      port: 9090
  replicaCount: 1
  ingressRoutes:
    - name: spongo
      url: iot.spongo.ru
      type: istio
      path: /
      service: iot-test-svc
      port: 8088
      className: nginx
  env:
    - name: MONGO_MONGODB_USERNAME
      value: mongoiot
    - name: MONGO_MONGODB_PASSWORD
      value: mongopass
    - name: MONGO_MONGODB_SERVER
      value: mongodb-svc
    - name: MONGO_MONGODB_DATABASE
      value: mongoiot      
configMap:
  - kakayatoperemennaya: dataone
  - vciakaya_fignia.yyy: mydata12345
  - perem-tree: dgkjfg
  - some-json: "{some json: 1234}"

integrations:
  - name: epk
    host: qwertyu.ru
    meshPort: 6666
    type: http
  - name: graphql
    host: malo.ru
    meshPort: 6667
    type: http
  - name: holdingcard
    host: holding.ru
    meshPort: 443
    type: https
    
istio:
  ingress:
    svc:
      name: iot-istio-ingress
      port: 4000
