{{- if .Values.tunnel.test.enable }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.24.0
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginxtun
  labels:
    pool: tunnel
    lbtype: {{ .Values.watcher.lbtype }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30411
  selector:
    app: nginx
  type: LoadBalancer

{{- end }}